version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=phongnh
      - DB_PASSWORD=phongnh
      - DB_NAME=stripe_golang
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: phongnh
      POSTGRES_PASSWORD: phongnh
      POSTGRES_DB: stripe_golang
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
